/// Flutter icons FontAwesomePro
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FontAwesomePro
///      fonts:
///       - asset: fonts/FontAwesomePro.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FontAwesomePro {
  FontAwesomePro._();

  static const _kFontFam = 'FontAwesomePro';
  static const String? _kFontPkg = null;

  static const IconData newspaper_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_day_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_day = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_days = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_info = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData curling = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gauge_max = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_start = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData memo_circle_check = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retweet = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bars = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
