/// Flutter icons FontAwesomePro
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FontAwesomePro
///      fonts:
///       - asset: fonts/FontAwesomePro.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FontAwesomePro {
  FontAwesomePro._();

  static const _kFontFam = 'FontAwesomePro';
  static const String? _kFontPkg = null;

  static const IconData calendar_day = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_days = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_range = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_star = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData canada_games = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData challenge = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_info = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_question = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_list_check = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData competition = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData curling = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diploma = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope_open_dollar = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gauge_max = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_heart = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handshake = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_start = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_card = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_resurfacer = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information_point = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData identity_card = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData landmark = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData job_search = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb_on = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_dot = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifying_glass = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manitoba_games = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manitoba_open = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_location_dot = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData memo_circle_check = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people_gauge_max = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people_gear = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people_group = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people_line = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData performance = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_chalkboard = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData podium_trophy = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData premium_badge = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retweet = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scoreboard = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen_users = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scroll = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_gears = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_check = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stick_curling = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData podium = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_headset = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData virus_covid = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whistle = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wreath = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_user = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badge_check = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bison = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bars = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullseye_arrow = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_clock = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
